jobs:
  cancel-existing:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: rokroskar/workflow-run-cleanup-action@v0.3.3
  test:
    needs: cancel-existing
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: 20
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm test
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: ignore
          name: Images from tests
          path: |-
            **/__image_snapshots__/__diff_output__
            test-results/*/**
      - if: matrix.os == 'ubuntu-latest' && matrix.node == 20
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

name: build
on:
  pull_request: {}
  push:
    branches:
      - master
